CREATE SCHEMA exercise1;

CREATE TABLE exercise1.EMP_1 
(EMP_NUM CHAR(3) PRIMARY KEY,
EMP_Lname VARCHAR(15),
EMP_FName VARCHAR(15),
EMP_INITIAL CHAR(1),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3) );

INSERT INTO exercise1.emp_1 (EMP_NUM, EMP_Lname, EMP_FName, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('125', 'ESCONDE', 'KON', 'R', '2002-11-13', 'DDD'),
	   ('163', 'KON', 'RAVSJJ', 'S', '2002-12-16', 'DDD');
       
SELECT * FROM exercise1.emp_1;

UPDATE exercise1.emp_1 SET JOB_CODE = '502' WHERE EMP_NUM = '125';

UPDATE exercise1.emp_1 SET JOB_CODE = '502' WHERE EMP_NUM = '163';

SELECT * FROM exercise1.emp_1;

DESCRIBE exercise1.emp_1 JOB_CODE;